const styles = {
  header: {
    height: '64px',
    backgroundColor: '#1e293b',
    borderBottom: '1px solid #334155',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '0 24px',
    position: 'fixed',
    top: 0,
    left: '240px',
    right: 0,
    zIndex: 99,
  },
  left: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    marginLeft: '20px',
  },
  pageTitle: {
    color: '#f1f5f9',
    fontSize: '18px',
    fontWeight: '600',
    margin: 0,
  },
  right: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
  },
  searchBox: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    backgroundColor: '#0f172a',
    border: '1px solid #334155',
    borderRadius: '8px',
    padding: '8px 14px',
    width: '220px',
  },
  searchInput: {
    backgroundColor: 'transparent',
    border: 'none',
    outline: 'none',
    color: '#f1f5f9',
    fontSize: '14px',
    width: '100%',
  },
  searchIcon: {
    fontSize: '14px',
    color: '#475569',
  },
  notifBtn: {
    width: '38px',
    height: '38px',
    borderRadius: '8px',
    backgroundColor: '#0f172a',
    border: '1px solid #334155',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    fontSize: '16px',
    color: '#94a3b8',
  },
  userBox: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    backgroundColor: '#0f172a',
    border: '1px solid #334155',
    borderRadius: '8px',
    padding: '6px 12px',
    cursor: 'pointer',
  },
  avatar: {
    width: '30px',
    height: '30px',
    borderRadius: '50%',
    backgroundColor: '#6366f1',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#fff',
    fontSize: '13px',
    fontWeight: 'bold',
  },
  userName: {
    color: '#f1f5f9',
    fontSize: '14px',
    fontWeight: '500',
  },
  userRole: {
    color: '#475569',
    fontSize: '12px',
  },
};

export default styles;